// Closed public projections: raw LMS objects never cross the content boundary.
export const fields = {
  documents: {
    module: "text",
    title: "text",
    type: "file",
    lmsHandle: "handle",
    downloadHandle: "optionalHandle",
  },
  recordings: {
    module: "text",
    title: "text",
    type: "externalTool",
    lmsHandle: "handle",
    launchHandle: "optionalHandle",
  },
  assignments: {
    title: "text",
    due_at: "text",
    remaining_candidate: "boolean",
    unlock_at: "text",
    lock_at: "text",
    points_possible: "number",
    published: "boolean",
    locked_for_user: "boolean",
    submission_workflow_state: "text",
    submitted_at: "text",
    missing: "boolean",
    late: "boolean",
    submission_types: "texts",
  },
  deadlines: { title: "text", due_at: "text", remaining_candidate: "boolean" },
  upcoming: {
    html_url: "optionalUrl",
    title: "text",
    date: "text",
    type: "text",
    course: "text",
    submitted: "boolean",
    new_activity: "boolean",
  },
  todo: {
    html_url: "optionalUrl",
    title: "text",
    due_at: "text",
    type: "text",
    course: "text",
    ignore: "boolean",
  },
} as const;
export const resultKey = {
  COURSES_LIST: "courses",
  ASSIGNMENTS_LIST: "assignments",
  DEADLINES_LIST: "deadlines",
  UPCOMING_LIST: "upcoming",
  TODO_LIST: "todo",
  RECORDINGS_LIST: "recordings",
  DOCUMENTS_LIST: "documents",
  RECORDING_OPEN: "opened",
  DOCUMENT_OPEN: "opened",
  DOCUMENT_DOWNLOAD: "downloaded",
} as const;
